<a href="https://colab.research.google.com/github/mahardikakdenie/Restricted-Boltzmann-Machine/blob/main/RBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing the libraries  
import numpy as np  
import pandas as pd  
import torch  
import torch.nn as nn  
import torch.nn.parallel  
import torch.optim as optim  
import torch.utils.data  
from torch.autograd import Variable

In [ ]:
movies = pd.read_csv('movies.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
print(movies)

         0                                   1                             2
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
...    ...                                 ...                           ...
3878  3948             Meet the Parents (2000)                        Comedy
3879  3949          Requiem for a Dream (2000)                         Drama
3880  3950                    Tigerland (2000)                         Drama
3881  3951             Two Family House (2000)                         Drama
3882  3952               Contender, The (2000)                Drama|Thriller

[3883 rows x 3 columns]


In [ ]:
Users = pd.read_csv('users.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')  
print(Users)

         0  1   2   3      4
0        1  F   1  10  48067
1        2  M  56  16  70072
2        3  M  25  15  55117
3        4  M  45   7  02460
4        5  M  25  20  55455
...    ... ..  ..  ..    ...
6035  6036  F  25  15  32603
6036  6037  F  45   1  76006
6037  6038  F  56   1  14706
6038  6039  F  45   0  01060
6039  6040  M  25   6  11106

[6040 rows x 5 columns]


In [ ]:
Ratings = pd.read_csv('ratings.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
print(Ratings)

            0     1  2          3
0           1  1193  5  978300760
1           1   661  3  978302109
2           1   914  3  978301968
3           1  3408  4  978300275
4           1  2355  5  978824291
...       ...   ... ..        ...
1000204  6040  1091  1  956716541
1000205  6040  1094  5  956704887
1000206  6040   562  5  956704746
1000207  6040  1096  4  956715648
1000208  6040  1097  4  956715569

[1000209 rows x 4 columns]


In [ ]:
# Preparing the training set and the test set  
training_set = pd.read_csv('u1.base', delimiter = '\t')
print(training_set)

         1   1.1  5  874965758
0        1     2  3  876893171
1        1     3  4  878542960
2        1     4  3  876893119
3        1     5  3  889751712
4        1     7  4  875071561
...    ...   ... ..        ...
79994  943  1067  2  875501756
79995  943  1074  4  888640250
79996  943  1188  3  888640250
79997  943  1228  3  888640275
79998  943  1330  3  888692465

[79999 rows x 4 columns]


In [ ]:
test_set = pd.read_csv('u1.test', delimiter = '\t')  
print(test_set)

         1     6  5  887431973
0        1    10  3  875693118
1        1    12  5  878542960
2        1    14  5  874965706
3        1    17  3  875073198
4        1    20  4  887431883
...    ...   ... ..        ...
19994  458   648  4  886395899
19995  458  1101  4  886397931
19996  459   934  3  879563639
19997  460    10  3  882912371
19998  462   682  5  886365231

[19999 rows x 4 columns]


In [ ]:
test_set = np.array(test_set, dtype = 'int')  
print(test_set)

[[        1        10         3 875693118]
 [        1        12         5 878542960]
 [        1        14         5 874965706]
 ...
 [      459       934         3 879563639]
 [      460        10         3 882912371]
 [      462       682         5 886365231]]


In [ ]:
training_set = np.array(training_set, dtype = 'int')  
print(training_set)

[[        1         2         3 876893171]
 [        1         3         4 878542960]
 [        1         4         3 876893119]
 ...
 [      943      1188         3 888640250]
 [      943      1228         3 888640275]
 [      943      1330         3 888692465]]


In [ ]:
# Getting the number of users and movies  
nb_users = int(max(max(training_set[:,0]), max(test_set[:,0])))  
print(nb_users)

943


In [ ]:
nb_movies = int(max(max(training_set[:,1]), max(test_set[:,1])))  
print(nb_movies)

1682


In [ ]:
max(training_set[:,1])  

1682

In [ ]:
max(test_set[:,1])  

1591

In [ ]:
# Converting the data into an array with users in lines and movies in columns  
def convert(data):
  new_data = []
  for id_users in range(1, nb_users + 1):  
    id_movies = data[:,1][data[:,0] == id_users]  
    id_ratings = data[:,2][data[:,0] == id_users]  
    ratings = np.zeros(nb_movies) 
    ratings[id_movies - 1] = id_ratings
    new_data.append(list(ratings))  
    return new_data
    training_set = convert(training_set)  
    test_set = convert(test_set)  

In [ ]:
# Converting the data into Torch tensors  
training_set = torch.FloatTensor(training_set)  
print(training_set)

In [ ]:
test_set = torch.FloatTensor(test_set)  
print(test_set)

In [ ]:
# Converting the ratings into binary ratings 1 (Liked) or 0 (Not Liked)  
training_set[training_set == 0] = -1
training_set[training_set == 1] = 0  
training_set[training_set == 2] = 0  
training_set[training_set >= 3] = 1  
test_set[test_set == 0] = -1  
test_set[test_set == 1] = 0  
test_set[test_set == 2] = 0  
test_set[test_set >= 3] = 1  

In [ ]:
# Creating the architecture of the Neural Network  
class RBM():  
    def __init__(self, nv, nh):
      self.W = torch.randn(nh, nv)
      self.a = torch.randn(1, nh) 
      self.b = torch.randn(1, nv) 
    def sample_h(self, x):  
      wx = torch.mm(x, self.W.t()) 
      activation = wx + self.a.expand_as(wx)  
      p_h_given_v = torch.sigmoid(activation)  
      return p_h_given_v, torch.bernoulli(p_h_given_v) 
    def sample_v(self, y):  
      wy = torch.mm(y, self.W)  
      activation = wy + self.b.expand_as(wy)  
      p_v_given_h = torch.sigmoid(activation)  
      return p_v_given_h, torch.bernoulli(p_v_given_h)  
    def train(self, v0, vk, ph0, phk):  
      self.W += torch.mm(v0.t(), ph0) - torch.mm(vk.t(), phk)  
      self.b += torch.sum((v0 - vk), 0)
      self.a += torch.sum((ph0 - phk), 0)  

In [ ]:
# Training the RBM  
nv = len(training_set[0]) 
nh = 100
batch_size = 100  
rbm = RBM(nv, nh)  
nb_epoch = 10
for epoch in range(1, nb_epoch + 1):  
  train_loss = 0 
  s=0
  for id_user in range(0, nb_users - batch_size, batch_size):  
    vk = training_set[id_user:id_user+batch_size]  
    v0 = training_set[id_user:id_user+batch_size]  
    ph0,_ = rbm.sample_h(v0)
    for k in range(10):  
      _,hk = rbm.sample_h(vk)
      _,vk = rbm.sample_v(hk)  
      vk[v0<0] = v0[v0<0]  
      phk,_ = rbm.sample_h(vk)  
      # rbm.train(v0, vk, ph0, phk)  
      train_loss += torch.mean(torch.abs(v0[v0>=0] - vk[v0>=0]))  
      s += 1.
      print('epoch: '+str(epoch)+' loss: '+str(train_loss/s)) 

In [ ]:
# Testing the RBM  
test_loss = 0  
s = 0
for id_user in range(nb_users):  
  v = training_set[id_user:id_user+1]  
  vt = test_set[id_user:id_user+1]  
  if len(vt[vt>=0]) > 0:  
    _,h = rbm.sample_h(v)  
    _,v = rbm.sample_v(h)
    test_loss += torch.mean(torch.abs(vt[vt>=0] - v[vt>=0]))  
    s += 1.  
    print('test loss: '+str(test_loss/s))  